# Generated by Django 3.2 on 2023-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_site_param_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='page_search_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
